### ISSUE TITLE
Will it be open-source or release some import parts of code?

### ISSUE THREAD

**Issue by foreverpiano** [kvcache-ai/Mooncake#1]

**Comment by james0zan** [comment]
Currently there is only plan of releasing traces. The implementation is deeply integrated into the whole serving platform, hard to open source only part of it. Thus code open source is not part of the plan in any near future.

**Comment by bet0x** [comment]
Then just close the repo, it is useless.

**Comment by alogfans** [comment]
The source code of Transfer Engine has released.
