### ISSUE TITLE
Source code compile and build

### ISSUE THREAD

**Issue by junna2016** [kvcache-ai/Mooncake#10]
When I compile from source code, it will meet an error when compile grpc process(grpc is on v1.27.3 branch). I done this in a nvcr.io/nvidia/pytorch:23.10-py3 docker environment, error is:

Mooncake/grpc/third_party/abseil-cpp/absl/synchronization/internal/graphcycles.cc: In member function ‘void absl::synchronization_internal::GraphCycles::RemoveNode(void*)’:
Mooncake/grpc/third_party/abseil-cpp/absl/synchronization/internal/graphcycles.cc:451:26: error: ‘numeric_limits’ is not a member of ‘std’
  451 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
      |                          ^~~~~~~~~~~~~~
Mooncake/grpc/third_party/abseil-cpp/absl/synchronization/internal/graphcycles.cc:451:49: error: expected primary-expression before ‘>’ token
  451 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
      |                                                 ^
Mooncake/grpc/third_party/abseil-cpp/absl/synchronization/internal/graphcycles.cc:451:52: error: ‘::max’ has not been declared; did you mean ‘std::max’?
  451 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
      |                                                    ^~~
      |                                                    std::max

**Comment by alogfans** [comment]
You may need to use export CXXFLAGS='-include /usr/include/c++/11.2.0/limits' for your Docker env (c.f. https://github.com/gpujs/gpu.js/issues/753). In addition, we prefer to use grpc from system's repository (such as apt-get install).

**Comment by junna2016** [comment]
> You may need to use export CXXFLAGS='-include /usr/include/c++/11.2.0/limits' for your Docker env (c.f. [gpujs/gpu.js#753](https://github.com/gpujs/gpu.js/issues/753)). In addition, we prefer to use grpc from system's repository (such as apt-get install).

I resolve this error by choosing a commit_id fixed absel version problems.
But when I try to compile Mooncake, error is:
![2](https://github.com/user-attachments/assets/eaebd36c-b19b-42e4-a821-a8c53c0878f8)

I have apt-get install libibverbs-dev, and set the LIBRARY_PATH/LD_LIBRARY_PATH for -libverbs

![3](https://github.com/user-attachments/assets/998626a5-779d-45b1-9b7e-f9d608cbaea7)

This error can reproduce with a simple test_verbs.c ， in which:
  #include <infiniband/verbs.h>
   #include <stdio.h>

   int main() {
       printf("libibverbs is installed and accessible.\n");
       return 0;
   }
   
   gcc -o test_verbs test_verbs.c -L /usr/lib/x86_64-linux-gnu -libverbs

**Comment by junna2016** [comment]
> You may need to use export CXXFLAGS='-include /usr/include/c++/11.2.0/limits' for your Docker env (c.f. [gpujs/gpu.js#753](https://github.com/gpujs/gpu.js/issues/753)). In addition, we prefer to use grpc from system's repository (such as apt-get install).

I resolved by change grpc codebase. Thanks a lot

**Comment by IEI-mjx** [comment]
Hi, @junna2016 
I also used this container, but failed when installing etcd-cpp-apiv3.
The above is error traceback,
```
CMake Error at /usr/lib/cmake/utf8_range/utf8_range-targets.cmake:86 (message):
  The imported target "utf8_range::utf8_validity" references the file

     "/usr/lib/libutf8_validity.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/cmake/utf8_range/utf8_range-targets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/cmake/utf8_range/utf8_range-config.cmake:7 (include)
  /usr/lib/cmake/protobuf/protobuf-config.cmake:12 (find_package)
  CMakeLists.txt:125 (find_package)
```
Have you encountered this error?
If possible, could you share your environment especially the versions of cmake, protobuf?
I would greatly appreciate your assistance.
