### ISSUE TITLE
ModuleNotFoundError: No module named 'mooncake_vllm_adaptor' 

### ISSUE THREAD

**Issue by tongyangyeyue** [kvcache-ai/Mooncake#13]
I followed the vllm-integration.md document and selected vLLM Python-only build (python3 python_only_dev.py)  to install，then i got this errors after "python3 -m vllm.entrypoints.openai.api_server"

```
Traceback (most recent call last):
  File "/root/anaconda3/envs/mooncake/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/root/anaconda3/envs/mooncake/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/ubuntu/vllm/vllm/__init__.py", line 3, in <module>
    from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
  File "/home/ubuntu/vllm/vllm/engine/arg_utils.py", line 11, in <module>
    from vllm.config import (CacheConfig, ConfigFormat, DecodingConfig,
  File "/home/ubuntu/vllm/vllm/config.py", line 12, in <module>
    from vllm.model_executor.layers.quantization import QUANTIZATION_METHODS
  File "/home/ubuntu/vllm/vllm/model_executor/__init__.py", line 1, in <module>
    from vllm.model_executor.parameter import (BasevLLMParameter,
  File "/home/ubuntu/vllm/vllm/model_executor/parameter.py", line 7, in <module>
    from vllm.distributed import get_tensor_model_parallel_rank
  File "/home/ubuntu/vllm/vllm/distributed/__init__.py", line 1, in <module>
    from .communication_op import *
  File "/home/ubuntu/vllm/vllm/distributed/communication_op.py", line 6, in <module>
    from .parallel_state import get_tp_group
  File "/home/ubuntu/vllm/vllm/distributed/parallel_state.py", line 40, in <module>
    import vllm.distributed.kv_transfer.vllm_adapter as dist_kv
  File "/home/ubuntu/vllm/vllm/distributed/kv_transfer/vllm_adapter.py", line 38, in <module>
    from vllm.distributed.kv_transfer.kv_pipe.mooncake_distributed_pipe import (
  File "/home/ubuntu/vllm/vllm/distributed/kv_transfer/kv_pipe/mooncake_distributed_pipe.py", line 8, in <module>
    import mooncake_vllm_adaptor as mva
ModuleNotFoundError: No module named 'mooncake_vllm_adaptor'
```
I can't find "mooncake_vllm_adaptor" anywhere, how can I install this dependency?

**Comment by ShangmingCai** [comment]
Please install the Mooncake Transfer Engine according to the [instructions](https://github.com/kvcache-ai/Mooncake/blob/main/doc/en/build.md) first.

Then check whether the `mooncake_vllm_adaptor.xxxx.so` is in your python `dist-packages` or `site-packages` dir.

**Comment by tongyangyeyue** [comment]
i find them ,thx

**Comment by CharlesJhonson** [comment]
Hi, how can I fix this ?  Could you help @ShangmingCai 
`ImportError: /home/miniforge3/envs/kvcache/lib/python3.10/site-packages/mooncake_vllm_adaptor.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN6google15ErrnoLogMessageC1EPKciiiMNS_10LogMessageEFvvE`

```
....
INFO 01-14 19:38:12 selector.py:129] Using XFormers backend.
ERROR 01-14 19:38:13 engine.py:366] Please install mooncake by following the instructions at https://github.com/kvcache-ai/Mooncake/blob/main/doc/en/build.md to run vLLM with MooncakeConnector.
ERROR 01-14 19:38:13 engine.py:366] Traceback (most recent call last):
ERROR 01-14 19:38:13 engine.py:366]   File "/home/miniforge3/envs/kvcache/lib/python3.10/site-packages/vllm/distributed/kv_transfer/kv_pipe/mooncake_pipe.py", line 57, in __init__
ERROR 01-14 19:38:13 engine.py:366]     import mooncake_vllm_adaptor as mva
ERROR 01-14 19:38:13 engine.py:366] ImportError: /home/miniforge3/envs/kvcache/lib/python3.10/site-packages/mooncake_vllm_adaptor.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN6google15ErrnoLogMessageC1EPKciiiMNS_10LogMessageEFvvE
ERROR 01-14 19:38:13 engine.py:366] 
ERROR 01-14 19:38:13 engine.py:366] The above exception was the direct cause of the following exception:
....
```

**Comment by ShangmingCai** [comment]
> Hi, how can I fix this ? Could you help @ShangmingCai `ImportError: /home/miniforge3/envs/kvcache/lib/python3.10/site-packages/mooncake_vllm_adaptor.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN6google15ErrnoLogMessageC1EPKciiiMNS_10LogMessageEFvvE`
> 

I wonder if you have installed mooncake transfer engine and vllm adapter according to the [guide](https://github.com/kvcache-ai/Mooncake/blob/main/doc/en/build.md). When installing, you need to build and install with your python env activated, so that the` .so` lib can be installed into the `site-packages` dir.

If the problem still exists, it may be related to your OS and the c++ lib when compiling.

**Comment by tongyangyeyue** [comment]
> Hi, how can I fix this ? Could you help @ShangmingCai `ImportError: /home/miniforge3/envs/kvcache/lib/python3.10/site-packages/mooncake_vllm_adaptor.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN6google15ErrnoLogMessageC1EPKciiiMNS_10LogMessageEFvvE`
> 
> ```
> ....
> INFO 01-14 19:38:12 selector.py:129] Using XFormers backend.
> ERROR 01-14 19:38:13 engine.py:366] Please install mooncake by following the instructions at https://github.com/kvcache-ai/Mooncake/blob/main/doc/en/build.md to run vLLM with MooncakeConnector.
> ERROR 01-14 19:38:13 engine.py:366] Traceback (most recent call last):
> ERROR 01-14 19:38:13 engine.py:366]   File "/home/miniforge3/envs/kvcache/lib/python3.10/site-packages/vllm/distributed/kv_transfer/kv_pipe/mooncake_pipe.py", line 57, in __init__
> ERROR 01-14 19:38:13 engine.py:366]     import mooncake_vllm_adaptor as mva
> ERROR 01-14 19:38:13 engine.py:366] ImportError: /home/miniforge3/envs/kvcache/lib/python3.10/site-packages/mooncake_vllm_adaptor.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN6google15ErrnoLogMessageC1EPKciiiMNS_10LogMessageEFvvE
> ERROR 01-14 19:38:13 engine.py:366] 
> ERROR 01-14 19:38:13 engine.py:366] The above exception was the direct cause of the following exception:
> ....
> ```

after i make mooncake in build directory，i find mooncake_vllm_adaptor.cpython-310-x86_64-linux-gnu.so in build/mooncake-integration，then copy mooncake_vllm_adaptor.cpython-310-x86_64-linux-gnu.so to my python lib /home/ubuntu/anaconda3/envs/mooncake/lib/python3.10/site-packages/

**Comment by CharlesJhonson** [comment]
Fixed!   
activate python env, and build, the copy to python lib dir.
thank you very much. @ShangmingCai  @tongyangyeyue

**Comment by pooyadavoodi** [comment]
I think this happens because `make install` copies the `so` file into `/usr/local/lib/` instead of the local venv directory.

**Comment by pooyadavoodi** [comment]
Just to help folks who follow the doc: https://github.com/kvcache-ai/Mooncake/pull/241
