### ISSUE TITLE
Questions about thread pool and shard

### ISSUE THREAD

**Issue by CharlesJhonson** [kvcache-ai/Mooncake#14]
Thanks for sharing the paper and code of this project! I have a question about the code:
What is the purpose of setting shard when there is already a worker_pool? What is the basis for setting the number to 8?

**Comment by alogfans** [comment]
The shard mechanism is designed to evenly distribute the user's RDMA requests among the different threads of the worker pool. In addition, if context_.cqCount() is greater than one, the shard mechanism also mitigates concurrent contention for some RDMA resources (QP and doorbell), which has more significant performance impact in small I/Os.

Setting the number to 8 is based on our experience.

**Comment by CharlesJhonson** [comment]
Thank you for your answer.
 If we want to avoid competition between QPs, shouldn't we consider assigning a CQ to each QP?

**Comment by alogfans** [comment]
Yes, so Mooncake supports allocating multiple CQs per device, which are assigned to QPs in a round-robin manner.

**Comment by CharlesJhonson** [comment]
Ok , thank you very much!
