### ISSUE TITLE
Why is there a transfer from prefill instance to decode instance inside a distributed kvcache? 

### ISSUE THREAD

**Issue by uniqueZt** [kvcache-ai/Mooncake#17]
hello，Why is there a transfer from prefill instance to decode instance inside a distributed kvcache? Are you worried about a lot of traffic crossing?

**Comment by ShangmingCai** [comment]
> hello，Why is there a transfer from prefill instance to decode instance inside a distributed kvcache? Are you worried about a lot of traffic crossing?

I'm sorry. I'm not sure about your real question, but I'll do my best to answer it. Currently, we have open-sourced the underlying transfer engine. But the mooncake store is still in progress. Therefore, in the disaggregated prefill/decode demo, the KVCache needs to be transferred from the prefill instance to the decode instance.

Also, although data transmission is mainly from the prefill instance to the decode instance, communication signals and metadata are still required between them.

**Comment by uniqueZt** [comment]
Okay, I mean in the architecture diagram, the DARM and SSD managed by the mooncake store should be similar to a distributed storage. Whether the internal transfer is to meet the network read overhead of the Prefill and decode stages as much as possible, that is, the local cache near the GPU, waiting for the open source of the overall system

![Uploading image.png…]()
