### ISSUE TITLE
Does mooncake work with one machine?

### ISSUE THREAD

**Issue by wxsms** [kvcache-ai/Mooncake#20]
Thank you for the awesome work in advance! I have a small question here, as the doc stat:

> Local memcpy: If the target Segment is actually in the local DRAM/VRAM, direct data copy interfaces such as memcpy, cudaMemcpy are used.

But I can not found any `cudaMemcpy` usage in the source code. When I try vLLM with Mooncake plus tcp protocol on 2 GPU connected by NVLink, the inference is quite slow on high QPS. Was this expected or how can I correctly configure this on single machine?

**Comment by alogfans** [comment]
The `local memcpy` feature in the doc is available if you use the RDMA protocol. (The TCP protocol does not implement this feature.) See [`mooncake-transfer-engine/src/transport/rdma_transport/worker_pool.cpp:199`](https://github.com/kvcache-ai/Mooncake/blob/e1479903367e484c4d547b3251b5f56df91c7c8e/mooncake-transfer-engine/src/transport/rdma_transport/worker_pool.cpp#L199). We are now testing VRAM-direct KVCache transfer and will release later.
