### ISSUE TITLE
proposal: add a new "http" metadata protocol

### ISSUE THREAD

**Issue by doujiang24** [kvcache-ai/Mooncake#29]
Glad to see https://github.com/kvcache-ai/Mooncake/pull/21 start to support multiple metadata servers.

Now, only etcd and redis are supported. I'm here to proposal a new "http" metadata type, benifits:
1. http metadata server are easy to deploy and scale.
2. the http metadata server could expose more APIs for system operator know/manage the system better.

Design:
The http server provide three restful APIs:
1. GET $metadata_uri?key=$key
2. PUT $$metadata_uri?key=$key, with json body
3. DELETE $metadata_uri?key=$key

If this does make sense, I'd like to have a try, thanks.

**Comment by alogfans** [comment]
Good idea! I think inheriting `TransferMetadataImpl` in `mooncake-transfer-engine/src/transfer_metadata.cpp` is enough :)
