### ISSUE TITLE
Small issue in trace

### ISSUE THREAD

**Issue by ruipeterpan** [kvcache-ai/Mooncake#3]
Thank you for open-sourcing the trace!

On line 13 of the .jsonl trace, there seems to be a small issue.
```
{"timestamp": 0, "input_length": 17448, "output_length":2748 610, "hash_ids": [0, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233]}
```
Here, `"output_length":2748 610` probably should have been just `"output_length": 610`?

**Comment by chestnut-Q** [comment]
Thanks for pointing out this mistake!

We've corrected the "output_length" to 610 on line 13. Appreciate your help!
