### ISSUE TITLE
Dose Mooncake support 2P1D architecture?

### ISSUE THREAD

**Issue by spxcds** [kvcache-ai/Mooncake#43]
I verified Qwen2.5-7B and Qwen2.5-72B models on NVIDIA-A800 and found that the performance is similar to that of no-disaggregate architecture.
DistServe's(https://hao-ai-lab.github.io/blogs/distserve/) experiments show that 2P1D architecture will boost performance.
I did not find any documentation about how to configure 2 prefill instances and 1 decode instance, does Mooncake support this method?

**Comment by ShangmingCai** [comment]
Upstream vllm currently only supports 1P1D for the disaggregated prefilling feature. XpYd is on the [roadmap](https://github.com/vllm-project/vllm/issues/10818) and will be supported soon. We will support this by building multiple connections between Xp and Yd, or we will support this through Mooncake's managed object-store.

**Comment by spxcds** [comment]
Thanks！
