### ISSUE TITLE
安装好费劲

### ISSUE THREAD

**Issue by WangErXiao** [kvcache-ai/Mooncake#47]
你们这个安装各种报错，能不能直接提供个镜像

**Comment by alogfans** [comment]
由于 Mooncake 目前处于快速演进的阶段，目前暂未提供镜像化部署包。关于部署困难的问题，建议您获取最新代码后，先尝试编译运行 Transfer Engine Bench 通过后再尝试使用 vLLM 对接。如硬件未安装 RDMA 网卡可使用TCP模式。

**Comment by WangErXiao** [comment]
OK
